### ISSUE TITLE
why not use local bot api

### ISSUE THREAD

**Issue by sheepweb** [sudospaes/rigel#1]
hello，What are the considerations for choosing to use client upload instead of local bot api?
https://grammy.dev/guide/api#configuring-grammy-to-use-the-local-bot-api-server

**Comment by x64abu** [comment]
Hello dear friend.
~You should know that Telegram bots have a file sending limit of up to 50 MB.~
~This is also mentioned in the grammy documentation, for example  `ctx.api.sendVideo()` or `ctx.replyWithVideo()` method:~

~Use this method to send video files, Telegram clients support mp4 videos (other formats may be sent as Document). On success, the sent Message is returned. Bots can currently send video files of up to 50 MB in size, this limit may be changed in the future.~


~To solve this issue, we need to send larger files using a Telegram client that has a 2GB limit.~

You bring up an interesting point. This seems interesting. I just realized it exists.

**Comment by x64abu** [comment]
The issue that arises seems to be that we need to compile the bot api first and then make sure to run it on the vps. It seems like it could make the development process a bit longer (if I'm wrong, please let me know ❤️).

**Comment by sheepweb** [comment]
My usual method is to use the aiogram/telegram-bot-api mirror, 
https://hub.docker.com/r/aiogram/telegram-bot-api
so that we can save the compilation process, 
and then point the bot api in the program to the mirror port we deployed.
```
version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "<api-id>"
      TELEGRAM_API_HASH: "<api-hash>"
      TELEGRAM_LOCAL: "True"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

volumes:
  telegram-bot-api-data:

```
